"""creazione db

Revision ID: 83682ff672f5
Revises: 
Create Date: 2026-05-27 16:40:36.268800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83682ff672f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('types', sa.Text(), nullable=True),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creatures')
    # ### end Alembic commands ###
